name: Daily Badge Assignment

on:
  schedule:
    # Runs daily at midnight UTC (adjust timezone as needed)
    - cron: "0 0 * * *"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  assign-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Call Badge Assignment API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            ${{ secrets.APP_URL }}/api/badge-assignments
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          APP_URL: ${{ secrets.APP_URL }}
